In [11]:
import pandas as pd
from Bio import AlignIO
import numpy as np

In [5]:
msa = AlignIO.read('/data/EBV/msas/splited/all150_sin_n_trimmed.fas','fasta')
length = 60000

In [101]:
startpoints

array([     1,  30001,  60001,  90001, 120001, 150001,   2532,  32532])

In [109]:
def pseudocircular(a,overlap):
    pseudocircular = np.pad(a, pad_width=(0, overlap-1), mode='wrap')
    return(pseudocircular)

def auto_split_points(msa,length,overlap = None):
    if overlap == None:
        overlap = int(round(length/2))

    ncols = msa.get_alignment_length()
    
    circular = np.arange(ncols)+1
    circular = pseudocircular(circular,overlap=length)
    
    ind_start = np.arange(start = 0,stop = len(circular)-1,step = overlap)
    ind_start = [i for i in ind_start if i<ncols]

    startpoints = circular[ind_start]

    ind_end = [j + length -1 for j in ind_start]
    endpoints = circular[ind_end]
    return(startpoints,endpoints)

In [111]:
start, end = auto_split_points(msa,length=60000)


In [98]:
auto_split_points(m)

[     0  30000  60000  90000 120000 150000 180000]
[59999, 89999, 119999, 149999, 179999, 209999, 239999]


In [14]:
rest = ncols % length 
slides = ncols/length

2

In [47]:
import numpy as np

def rolling_window(a, window):
    # http://www.mail-archive.com/numpy-discussion@scipy.org/msg29450.html
    shape = a.shape[:-1] + (a.shape[-1] - window + 1, window)
    strides = a.strides + (a.strides[-1],)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

def circular_rolling_window(a, window):
    pseudocircular = np.pad(a, pad_width=(0, windowsize-1), mode='wrap')
    return rolling_window(pseudocircular, windowsize)



In [62]:
l = 34
a = np.arange(l)
size = 11
circ = pseudocircular(a,overlap = 4)
step = np.round(size/2)
nwind = np.ceil(l/step)

6.0

In [112]:
if not False:
    print 3

3


In [63]:
np.linspace(1,l,nwind)

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: object of type <type 'numpy.float64'> cannot be safely interpreted as an integer.
  """Entry point for launching an IPython kernel.


array([  1. ,   7.6,  14.2,  20.8,  27.4,  34. ])

In [26]:
pseudocircular

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3])

In [27]:
shape = a.shape[:-1] + (a.shape[-1] - window + 1, window)
shape

(6, 5)

In [23]:
strides = a.strides + (a.strides[-1],)
strides

(8, 8)

In [28]:
np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [44]:
np.lib.stride_tricks.as_strided(a,shape=(2,7),strides=(2,2))

array([[              0, 281474976710656,      4294967296,           65536,
                      1, 562949953421312,      8589934592],
       [281474976710656,      4294967296,           65536,               1,
        562949953421312,      8589934592,          131072]])

In [41]:
a.strides + (a.strides[-1],)

(8, 8)

(8,)